module.exports = {
	RECEIVE_PROJECTS: 'RECEIVE_PROJECTS',
	RECEIVE_LISTS:    'RECEIVE_LISTS',
	RECEIVE_TASKS:    'RECEIVE_TASKS',
	RECEIVE_TASK:     'RECEIVE_TASK',

	// SAVE_ORDER: 'SAVE_ORDER',
	ADD_TASK:   'ADD_TASK',

	RECEIVE_USER: 'RECEIVE_USER',
};
